on: 
  workflow_call:
    inputs:
      phpversion:
        required: true
        type: string
      nodeversion:
        required: true
        type: string

name: CI
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    needs:
      - phpunit
    services:
      mariadb:
        image: mariadb:10.6.4
        ports:
          - 3306
        env:
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_DATABASE: db_test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.phpversion }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeversion }}
      - name: Setup yarn
        run: npm install -g yarn
      - name: Create .env.test.local
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          echo "DATABASE_URL=\"mysql://db:db@127.0.0.1:${DB_PORT}/db?serverVersion=mariadb-10.3.31&charset=utf8mb4\"" > .env.test.local
      - run: make all
        name: Build Project
      - run: make check_preps
        name: Testvorbereitungen
      - run: php -d xdebug.mode=coverage ./vendor/bin/phpunit --coverage-html coverage --coverage-clover clover.xml
        name: Get Codecoverage Report
      - name: Comment Code Coverage
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./clover.xml
      - uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: coverage
          path: coverage
